### PR TITLE
Revert "ccnl-riot: initialize fields for default options"

### PR DESCRIPTION
**Pull request by blacksheeep**
Reverts cn-uofbasel/ccn-lite#209

### CODE REVIEW

**Comment by cgundogan** [comment]
There's no need to revert the full commit.
```
default_opts.ndntlv.interestlifetime = CCNL_INTEREST_TIMEOUT;
```

This just needs to be
```
CCNL_INTEREST_TIMEOUT * 1000
```

if I am not mistaken.

[struct ccnl_interest_s -> interestlifetime](https://github.com/cn-uofbasel/ccn-lite/blob/master/src/ccnl-core/include/ccnl-interest.h#L42) is in seconds, while
[struct ccnl_ndntlv_interest_opts_s -> interestlifetime](https://github.com/cn-uofbasel/ccn-lite/blob/master/src/ccnl-pkt/include/ccnl-pkt-ndntlv.h#L122) is in milliseconds.

AFAIK there's no way to interact with `struct ccnl_interest_s -> interestlifetime` from a user and even developer perspective through the API. Did I miss something?

**Comment by mfrey** [comment]
> struct ccnl_interest_s -> interestlifetime is in seconds, while
struct ccnl_ndntlv_interest_opts_s -> interestlifetime is in milliseconds.

So, this means that these two variables refer to "different" (but related) topics? The first is more about  a timeout of an interest (no matter which ICN flavor) and the latter is specific to NDN? Honestly, this is kind-of confusing (and also explains why @OlegHahm assigned ``default_opts.ndntlv.interestlifetime`` a default value of ``CCNL_INTEREST_TIMEOUT`` (which again is the wrong default (it is 4 seconds and not 10 seconds)).

But, maybe I'm missing something and just need more sleep.

**Comment by blacksheeep** [comment]
Ok, but the incorrect default value does not effect the functionality nor the interoperability with NDN.

Somehow, at this point I did not get the problem at all. 
You want the timeouts to be specified in Milliseconds? I think that would be a complete different issue and not influencing this pull request since it applies the default value.
Moreover, is there a really benefit from having the timeout in Milliseconds? 
The lifetime of an interest is always a combination of retransmit and timeouts, and relies on the required RTT which is usually be hard to guess in a more precise way than seconds. 

If we have arguments to change that to Milliseconds, I am open to do so. 
But again, does this influence this PR?

**Comment by cgundogan** [comment]
```c
default_opts.ndntlv.interestlifetime = CCNL_INTEREST_TIMEOUT;
```

at least this needs to be changed to milli seconds, because the `default_opts.ndntlv.interestlifetime` value is directly written to the outgoing Interest message. There it is supposed to be milli seconds

**Comment by blacksheeep** [comment]
ok, now I get close to the issue, so having this, we will end up with inconsistencies?

**Comment by mfrey** [comment]
This is generating more "fuzz" than it should be. I would suggest to define a constant 
```C
/**
 * Default interest lifetime in milliseconds. If the element is omitted by a user, a default 
 * value of 4 seconds is used.
 */
#ifndef NDN_DEFAULT_INTEREST_LIFETIME
#define NDN_DEFAULT_INTEREST_LIFETIME (4000u)
#endif
```
and assign it to the default initialisation. I would also to suggest to postpone the whole (internal?) lifetime discussion and update #210

**Comment by blacksheeep** [comment]
See PR #216

**Pull request closed without merging**
