### PR TITLE
ccn-lite-riot.c: reuse ccnl_ndntlv_forwarder to send interests

### PR DESCRIPTION
**Pull request by cgundogan**
The current implementation does not honor the local cache when emitting
interests. By reusing the `ccnl_ndntlv_forwarder()` function, the local
cache is checked before propagating the interest.

### CODE REVIEW

**Comment by blacksheeep** [comment]
Since we know that the packet is a interest in any case, wouldn't it be enough to call "ccnl_fwd_handleInterest"?

**Comment by cgundogan** [comment]
@blacksheeep thanks for the hint; it makes more sense to use `ccnl_fwd_handleInterest()` directly. I also modified the return value of `ccnl_send_interest()` from `struct ccnl_interest_s *` to `int`, because there is no `struct ccnl_interest_s *` in the context of the function anymore.

**Comment by PeterKietzmann** [comment]
Works as expected. Don't forget to change the header in RIOT!

**Comment by blacksheeep** [comment]
@PeterKietzmann @cgundogan  so I can apply this patch?

**Comment by cgundogan** [comment]
@blacksheeep yup, no ned to wait for @OlegHahm's review here (:

**Pull request merged**
