### PR TITLE
add ipv6 support

### PR DESCRIPTION
**Pull request by OlegHahm**
This PR adds a new macro called `USE_IPV6` that enables IPv6 support for ccn-lite. It should not have any impact on old applications,

Currently this PR also includes changes to [ccn-lite-relay.c](https://github.com/cn-uofbasel/ccn-lite/blob/master/src/ccn-lite-relay.c) as a showcase, but I can remove these changes before merging if needed.

### CODE REVIEW

**Comment by OlegHahm** [comment]
I think the Travis fail is related to the half-hearted ccn-lite-relay.c change that is meant to be removed any way.

**Comment by OlegHahm** [comment]
Oops, that was not meant for merging yet. Will prepare a PR that revert the changes to ccn-lite-relay.c in order to get Travis working.

**Comment by blacksheeep** [comment]
I applied the patch for now, but I enabled IPv4 per default. 
Our test script expect IPv4 addresses. 

Thanks

**Comment by OlegHahm** [comment]
ok, great, thx

**Pull request merged**
