### PR TITLE
introduces size_t over int in length parameters/variables, improves code quality, safer usage of stdlib

### PR DESCRIPTION
**Pull request by blacksheeep**
Solve a lot of security issues:

* use size types
* safer usage of stdlib / string - lib
* better coding styling.

### CODE REVIEW

**Comment by cgundogan** [comment]
what is it saying when you try to squash?

**Comment by blacksheeep** [comment]
I get some wired conflicts, and it has some strange merge conflicts - I
have no idea why.

**Comment by mfrey** [comment]
> I get some wired conflicts, and it has some strange merge conflicts - I
have no idea why.

I'll have a look later

**Comment by mfrey** [comment]
We've had a brief discussion in #334 on ``bool`` (which was introduced in C99) and CCN-lites support for the Linux kernel (which in turn does not support C99). I've went over a few files and noticed that in some files a ``bool`` type is used (which probably results in issues in the Linux frontend of CCN-lite), i.e.
```bash
src/ccnl-core/include/ccnl-content.h:#include <stdbool.h>
src/ccnl-core/include/ccnl-pkt-util.h:#include <stdbool.h>
src/ccnl-core/include/ccnl-pkt-util.h:bool
src/ccnl-core/include/ccnl-pkt.h:#include <stdbool.h>
src/ccnl-core/include/ccnl-pkt.h:    bool mbf;
src/ccnl-core/src/ccnl-pkt-util.c:bool
src/ccnl-pkt/include/ccnl-pkt-ndntlv.h:#include <stdbool.h>
src/ccnl-pkt/include/ccnl-pkt-ndntlv.h:    bool mustbefresh;           /**< MustBeFresh Selector */
```
Do you consider this as an issue as well and should create an issue? It does not necessarily affect the PR (haven't checked if some of it was introduced with the PR).

**Comment by blacksheeep** [comment]
Hmmm I could compile it now, but I will change the bools.

**Comment by blacksheeep** [comment]
I addressed the bools.

**Pull request closed without merging**
